name: Type-State presentation

on:
  push:

jobs:
  demo:
    name: Type-State presentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.7.0

      - name: Compile presentation
        run: devbox run build

      - name: Upload presentation
        uses: actions/upload-artifact@v3
        with:
          name: presentation
          path: presentation.html
          if-no-files-found: error
